name: on_merge
on:
  pull_request:
    types:
      - closed
    branches:
      - main
jobs:
  prepare:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Cache node modules
        id: cache
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: cache-node-modules-${{ hashFiles('yarn.lock') }}
      - name: yarn install
        run: |
          yarn install
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Cache node modules
        id: cache
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: cache-node-modules-${{ hashFiles('yarn.lock') }}
      - uses: fregante/daily-version-action@v2
        id: daily-version
      - name: build
        run: yarn build
      - name: Update manifest.json
        run: |
          npx dot-json@1 dist/manifest.json version ${{ steps.daily-version.outputs.version }}
      - name: Archive
        run: |
          zip -r extension.zip ./dist
      - name: Check Archive
        run: |
          rm -rf ./dist
          unzip extension.zip
          ls -lR ./dist
      - name: Submit
        run: |
          npx chrome-webstore-upload-cli@2 upload --source extension.zip --auto-publish
        env:
          EXTENSION_ID: ${{ secrets.EXTENSION_ID }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
      - name: Create release draft
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.daily-version.outputs.version }}
          draft: false
          generate_release_notes: true
          files: extension.zip
